# Default calendar configuration.
# Store in "~/.config/calendar", "/etc/xdg/calendar", "/etc/calendar".

# Colors can be specified in a few different ways. Terminal support may vary.
# By default, all colors are specified using ANSI 16 which has the best support.
#
# ANSI 16 colors: "5", "9", "12" (numbers 0-15)
# ANSI 256 Colors: "86", "201", "202" (numbers 16-255)
# True Color (16,777,216 colors; 24-bit): "#0000FF", "#04B575", "#3C3C3C"
TodayColor = "2"
InactiveColor = "8"

# We use one more padding on the left to account for the border around the
# preview window. Looks a bit unbalanced without it, but feel free to tweak as
# you please.
LeftPadding = 2
RightPadding = 1

# NotePath should describe where the note would be located for this predefined
# time:
# January 2, 15:04:05, 2006, in time zone seven hours west of GMT
#
# Environment variable, such as $HOME may be used in the path and will be
# expanded appropriately. If the file is missing it is simply treated as an
# empty file. All other errors will return the error string itself (which is
# meant to be displayed to the user).
NotePath = "$HOME/.local/share/calendar/2006-01-02.md"

# You may specify an editor to use when opening notes. If unspecified, we will
# respect the environment variables VISUAL or EDITOR or fallback to using vi.
# Editor = "nvim"

# Padding, LeftMargin, MinWidth, and MaxWidth for the preview window.
#
# Padding and margin are included within min and max width.
# Unit is number of spaces.
PreviewPadding = 1
PreviewLeftMargin = 3
PreviewMinWidth = 40
PreviewMaxWidth = 80

# You can change the hotkeys used to navigate the calendar. The key names are
# mostly as you would expect, but you may refer to this list for "the strange
# ones":
# https://github.com/charmbracelet/bubbletea/blob/94d6f5079e07301046e38f6c59cb286dd6856155/key.go#L245
KeySelectLeft=["left", "h"]
KeySelectDown=["down", "j"]
KeySelectUp=["up", "k"]
KeySelectRight=["right", "l"]
KeyFocusPreview=["tab"]
KeyTogglePreview=["p"]
KeyEditNote=["enter"]
KeyYankDate=["y"]
KeyLastSunday=["b", "H"]
KeyNextSunday=["w"]
KeyNextSaturday=["e", "L"]
KeyMonthUp=["ctrl+u"]
KeyMonthDown=["ctrl+d"]
